### PR TITLE
Replace deprecated node-sass package with sass

### PR DESCRIPTION
**Pull request by ivanoats**
[Node-sass](https://sass-lang.com/blog/libsass-is-deprecated) is not being maintained anymore, and the recommended replacement is [Dart-sass](https://sass-lang.com/dart-sass), which is the primary JavaScript sass package.

- feat: replace deprecated node-sass with sass
- fix: remove outdated UI libraries

### CODE REVIEW

**Review by neo — APPROVED** [review]
Thanks!

**Comment by AgainPsychoX** [comment]
@neo When can we get this merged?

**Comment by AgainPsychoX** [comment]
@pastelsky When can we get this merged??

**Comment by AgainPsychoX** [comment]
@pastelsky ETA ?

**Comment by AgainPsychoX** [comment]
@pastelsky ?

**Comment by gm-santos** [comment]
THANKS @ivanoats <3

**Comment by AgainPsychoX** [comment]
@pastelsky ???

**Comment by AgainPsychoX** [comment]
@pastelsky Hey, its almost month already, since I really really really really need it to be fixed. How about you at least do funny prank for April 1st by announcing you will look into it? Sadge

**Comment by pastelsky** [comment]
Thanks for contributing. I believe that an upgrade to sass and sass-loader was done recently, so the objective is reached.

**Pull request closed without merging**
