### PR TITLE
Add loader for support for react-native-* ecosystem

### PR DESCRIPTION
**Pull request by retyui**
A lot of react-native and expo modules published code as ES6 modules with JSX 
To fix it I add specific loaders that solve this problem. 

### To test just run 

```sh
curl 'localhost:3000/size?p=react-native-maps'
curl 'localhost:3000/size?p=react-native-share'
curl 'localhost:3000/size?p=expo-ads-admob'
```

### Commands above throw error (on `master` branch):
```js
 {
  name: 'BuildError',
  originalError: [
    '/tmp/tmp-build/packages/build-react-native-share-Tpe/node_modules/react-native-share/index.js 18:12\n' +
      'Module parse failed: Unexpected token (18:12)\n' +
      'File was processed with these loaders:\n' +
      ' * ./node_modules/shebang-loader/index.js\n' +
      'You may need an additional loader to handle the result of these loaders.\n' +
      '|   PermissionsAndroid,\n' +
      "| } from 'react-native';\n" +
      "> import type { ViewStyleProp } from 'react-native/Libraries/StyleSheet/StyleSheet';\n" +
      '| \n' +
      "| import Overlay from './components/Overlay';\n" +
      ' @ /tmp/tmp-build/packages/build-react-native-share-Tpe/index.js 1:10-39'
  ],
  extra: undefined
}
```

### CODE REVIEW

**Comment by retyui** [comment]
Based on https://github.com/pastelsky/bundlephobia/issues/279

**Comment by retyui** [comment]
@pastelsky Hi

**Comment by retyui** [comment]
@pastelsky HI!!!

**Comment by pastelsky** [comment]
React native libs are usually bundled by a separate bundler — metro. I don't think using webpack for these would give an accurate picture.

**Comment by retyui** [comment]
metro used a babel under the hood to transpile the code

**Comment by pastelsky** [comment]
Right, but bundling is about more than just babel. And the babel
configuration used matter too.

**Comment by retyui** [comment]
@pastelsky Please merge this PR!

**Pull request closed without merging**
